spring.application.name=Car-Recommend

spring.datasource.url=jdbc:postgresql://db.nucqborscmzmoxsfguro.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=contraseña123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
